### ISSUE TITLE
FR: Settings for ignoring words

### ISSUE THREAD

**Issue by chrisgrieser** [nothingislost/obsidian-highlight-current-word#4]
highlighting words such as `the` is adding a bit of unnecessary noise, so I'd suggest adding an option to configure words to ignore. (Could also be solved via CSS, when the css class `.current-word` gets a data-attribute).

I'd suggest adding a [stop list](https://www.wikiwand.com/en/Stop_word) of English words as default words to ignore, e.g. https://gist.github.com/sebleier/554280

**Comment by nothingislost** [comment]
Addressed in 0.0.5

**Comment by chrisgrieser** [comment]
works great! two things that could be make it a bit better though:
1. make the setting for ignored words a textarea and not an input element, since the latter is really hard to edit with so many words in it
2. the ignored words list should probably be case insensitive to catch words like "the" being at capitalized at the beginning of a sentence. Right now a "The" still triggers the plugin

<img width="571" alt="Screenshot 2021-12-29 23 51 55" src="https://user-images.githubusercontent.com/73286100/147709116-6fc82b21-03bc-4a3d-ae1d-7fe549491163.png">

**Comment by nothingislost** [comment]
Addressed in 0.0.6

**Comment by chrisgrieser** [comment]
works fine :)
